### ISSUE TITLE
Remove hack when DowngradeCovariantReturnTypeRector issue is fixed in Rector

### ISSUE THREAD

**Issue by leoloso** [leoloso/PoP#1470]
When this issue is fixed in Rector:

- https://github.com/rectorphp/rector/issues/6962

Then remove this hack from `generate_plugins.yml`:

```yml
################################################################################
# Temporary hack: fix the return type in Trait, not yet handled by Rector
# @see https://github.com/rectorphp/rector/issues/6962
# @see https://github.com/leoloso/PoP/issues/1470
-   name: Temporary hack - fix the return type in Trait
    run: |
        sed -i 's/function getItem($key): CacheItem/function getItem($key): \\Psr\\Cache\\CacheItemInterface/' vendor/symfony/cache/Traits/AbstractAdapterTrait.php
    working-directory: ${{ matrix.pluginConfig.path }}
    if: ${{ matrix.pluginConfig.scope }}
################################################################################
```
