### ISSUE TITLE
Convention over configuration

### ISSUE THREAD

**Issue by leoloso** [leoloso/PoP#196]
# Feature Request

There is a series of objects that are initialized through Symfony's DependendencyInjection components, such as:

- TypeResolvers
- FieldResolvers
- Hooks
- others

In all packages, these are generally placed under the same folders:

- `src/TypeResolvers`
- `src/FieldResolvers`
- `src/Hooks`
- etc

They are registered in the package's `Component.php` file:

```php
class Component extends AbstractComponent
{
    use YAMLServicesTrait;

    public static function beforeBoot(): void
    {
        parent::beforeBoot();

        ContainerBuilderUtils::registerTypeResolversFromNamespace(__NAMESPACE__ . '\\TypeResolvers');
        ContainerBuilderUtils::attachFieldResolversFromNamespace(__NAMESPACE__ . '\\FieldResolvers');
        ContainerBuilderUtils::instantiateNamespaceServices(__NAMESPACE__ . '\\Hooks');
    }
}
```

And they must be added to `config/services.yaml`:

```yaml
services:
    _defaults:
        public: true
        autowire: true

    GraphQLByPoP\GraphQLServer\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    GraphQLByPoP\GraphQLServer\TypeResolvers\:
        resource: '../src/TypeResolvers/*'

    GraphQLByPoP\GraphQLServer\Hooks\:
        resource: '../src/Hooks/*'
```

This code is always the same, so it makes sense for the framework to already know how to register the entities, and already register them whenever they exist.

Then, we can make make those subnamespaces be reserved:

- `TypeResolvers`
- `FieldResolvers`
- `Hooks`
- etc

And all classes under them are automatically registered by the framework, without having to manually define the code in `Component.php` and `services.yaml`.

Things to consider for the implementation:

- Conditional classes are also placed under these folders, such as `graphql-server/src/FieldResolvers/ConditionalOnEnvironment/EmbeddableFields/EchoOperatorGlobalFieldResolver.php`. These must be moved out to a different subnamespace:
  - from: `FieldResolvers/Conditional`
  - to: `ConditionalFieldResolvers`
- The `service.yaml` can be provided instead as a `service.php`, so it can contain logic. This works for both the framework (eg: to check if there are classes on each of the reserved namespaces) and the package (eg: to define custom services using their accessed PHP class, not as a string)

## Context

It reduces the code to start a project, and by imposing common conventions we also avoid bugs (for instance, when we forget to declare a service in the yaml config file)
