### ISSUE TITLE
Remove hack to bypass Composer issue

### ISSUE THREAD

**Issue by leoloso** [leoloso/PoP#2249]
See: https://github.com/composer/composer/issues/11458

When that issue is fixed, remove the following code in `.github/workflows/generate_plugins.yml`:

```yaml
            # Avoid Composer bug: https://github.com/composer/composer/issues/11458
            -   name: Delete `composer.lock`
                run: rm composer.lock
                working-directory: ${{ matrix.pluginConfig.path }}
```
