### ISSUE TITLE
Once Rector is available on PHP 7.1: Use it for testing downgrades

### ISSUE THREAD

**Issue by leoloso** [leoloso/PoP#299]
Continuation from PR #296.

After downgrading to PHP 7.1, we are now testing the downgraded code for the dependencies too.

However, we can't use PHPStan anymore:

```bash
vendor/bin/phpstan analyse build/downgraded-code --level 0
```

Because [there are dependencies that do not pass it](https://github.com/leoloso/PoP/runs/1667104694?check_suite_focus=true). Hence, this code has been removed.

As alternative, we can run Rector on the downgraded code instead, using PHP 7.1. Then, if there's any PHP 7.2+ code leftover, Rector will complain when running the process.

However, Rector for PHP 7.1 is not ready yet: https://github.com/rectorphp/rector/pull/4447

Once ready, enable it to do the testing, by uncommenting [this code from `generate_plugin.sh`](https://github.com/leoloso/PoP/blob/4130cc1411e83001a0c69bfda790925d69c707d8/layers/GraphQLAPIForWP/plugins/graphql-api-for-wp/.github/workflows/generate_plugin.yml#L122):

```yaml
#   run: vendor/bin/rector-php71 process build/downgraded-code --ansi --dry-run
```

**Comment by leoloso** [comment]
Must also fix this code, in all `downgrade_php_tests.yml`:

```yaml
      # @todo Fix this code
      # @see https://github.com/leoloso/PoP/issues/299
      - name: Run Rector on PHP 7.1
        run: echo "Running Rector on PHP 7.1 must be enabled, once available (https://github.com/leoloso/PoP/issues/299)"
      #   run: vendor/bin/rector-php71 process src vendor --ansi --dry-run
```
